version: '2'

services:
  board-proxy:
    image: eugenekha/board-proxy:latest
    volumes:
      - /content/board/board-proxy/src:/usr/share/nginx/html
      - /content/board/board-proxy/nginx:/etc/nginx
    #ports:
    #  - "8088:8080"
    network_mode: "bridge"
  #environment:
  # - NGINX_HOST=foobar.com
  # - NGINX_PORT=80
    #command: nginx -g 'daemon off;'